# config.yaml
rooms:
  - name: Main
    # objects is an empty list
    objects: []
    doorkeys:
      - name: KeyA
        forroom: Room1
  - name: Room1
    objects:
      - name: Chair
      - name: Ball
    doorkeys:
      - name: KeyB
        forroom: Room2
  - name: Room2
    objects:
      - name: Table
    doorkeys: []
