# config.yaml
rooms:
  - name: Room1
    dimensions: (0,0,4,4)
    doors:
      - name: Door1
        location: (4,2)
        layout: vertical
    objects:
      - name: Chair
        location: (2,2)
  - name: Room2
    dimensions: (0,4,4,8)
    doors:
      - location: (0,4)
        layout: vertical
    objects:
      - name: Table
        location: (2,6)
